version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI=$REPOSITORY_URI
  build:
    commands:
      - echo Build started on `date`
      - docker build -t image:latest .
      - docker tag image:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo we are in post_build now.
      - docker push $REPOSITORY_URI:latest
      - printf '[{"name":"kudi","imageUri":"%s"}]' $REPOSITORY_URI:latest > imagedefinition.json
artifacts:
  files:
    - imagedefination.json
    - taskdef.json
    - '**/*'
