version: "3.7"

services:
  server:
    build:
      context: ./
    container_name: kudi
    image: kudi
    ports:
      - "3900:3900"
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DATABASE: kudi_db
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
    networks:
      - backend
    links:
      - mongodb
    depends_on:
      - mongodb

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - backend

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "kudi-operation:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
